<?php

$cities = [
	"Agoura Hills",
	"Alhambra",
	"Arcadia",
	"Artesia",
	"Avalon",
	"Azusa",
	"Baldwin Park",
	"Bell",
	"Bellflower",
	"Beverly Hills",
	"Bradbury",
	"Burbank",
	"Calabasas",
	"Carson",
	"Cerritos",
	"Claremont",
	"Commerce",
	"Compton",
	"Covina",
	"Cudahy",
	"Culver City",
	"Diamond Bar",
	"Downey",
	"Duarte",
	"El Monte",
	"El Segundo",
	"Gardena",
	"Glendale",
	"Glendora",
	"Hawaiian Gardens",
	"Hawthorne",
	"Hermosa Beach",
	"Hidden Hills",
	"Huntington Park",
	"Industry",
	"Inglewood",
	"Irwindale",
	"La Cañada Flintridge",
	"La Habra Heights",
	"La Mirada",
	"La Puente",
	"La Verne",
	"Lakewood",
	"Lancaster",
	"Lawndale",
	"Lomita",
	"Long Beach",
	"Los Angeles title",
	"Lynwood",
	"Malibu",
	"Manhattan Beach",
	"Maywood",
	"Monrovia",
	"Montebello",
	"Monterey Park",
	"Norwalk",
	"Palmdale",
	"Palos Verdes Estates",
	"Paramount",
	"Pasadena",
	"Pico Rivera",
	"Pomona",
	"Rancho Palos Verdes",
	"Redondo Beach",
	"Rolling Hills",
	"Rolling Hills Estate",
	"Rosemead",
	"San Dimas",
	"San Fernando",
	"San Gabriel",
	"San Marino",
	"Santa Clarita",
	"Santa Fe Springs",
	"Santa Monica",
	"Sierra Madre",
	"Signal Hill",
	"South El Monte",
	"South Gate",
	"South Pasadena",
	"Temple City",
	"Torrance",
	"Vernon",
	"Walnut",
	"West Covina",
	"West Hollywood",
	"Westlake Village",
	"Whittier"
];

